### ISSUE TITLE
No longer plays movies

### ISSUE THREAD

**Issue by redlikemethodz** [m0ngr31/kodi-alexa#100]
I set everything up with this code about a week ago and it all worked fine.  Now for some reason I can do everything but play movies.  I can select, pause, etc.  But when I say "Alexa, tell Kodi to play [Movie]."  I get: "Playing Videos is not supported on this device."  I can verify in my Alexa history that it converted my voice to the right words.  Please help.

**Comment by jingai** [comment]
The incantation, currently, is:

"Alexa, tell Kodi to play *movie* [movie]", or,
"Alexa, tell Kodi to watch *movie* [movie]"

You have to specify the media type (see the italicized text there).  This will change eventually, but currently it is required.

**Comment by m0ngr31** [comment]
I've been getting the same issue the last week or so for the following (on the 2.5 branch):

'Alexa, tell Kodi to play an episode of always sunny in Philadelphia.'
"Playing Videos is not supported on this device"

'Alexa, tell kodi to steam music by the xx.'
(Starts playing the xx from spotify)

I don't know if there was an update or something, but this has started happening pretty suddenly. Alexa is trying to get too clever. The history shows that it heard exactly what I said, but it didn't invoke the correct skill.

What I've had to do to get around this is to update the branch to keep the session open after kodi is invoked: 'Alexa, open kodi... (Wait for response, and then insert command here)'. That has worked flawlessly so far.

**Comment by jingai** [comment]
Weird.. I haven't personally had any issues lately.  Is there any difference for you between tell and ask?  I have seen that on occasion before, but not recently.

Though, to be clear:  what I said in my first response still stands.  You do currently have to specify the media type.  I've had the behavior you're mentioning if I don't.

**Comment by redlikemethodz** [comment]
Sorry I meant to say ...Movie [movie] in my original post. I am specifying media type.

**Comment by jingai** [comment]
Could you let us know if you see a difference between "Alexa, tell Kodi..." and "Alexa, ask Kodi..."?

**Comment by redlikemethodz** [comment]
There's no difference. I tried all the utterances.

**Comment by jingai** [comment]
How many movies do you have in your library?  Are they in the MOVIES slot?

**Comment by redlikemethodz** [comment]
It hovers around 230. They are are all in the movie slot.

**Comment by gustavoatar** [comment]
I am having the same issue, do you think it has something to do with Alexa preparing itself for its own UI connected to Amazon Video?  I found that the way i got it to work is by saying partial movie names, which is weird but still works, is anyone else able to fix it doing this?

**Comment by jingai** [comment]
Is this still happening for you guys?  I have yet to see this problem here.

**Comment by redlikemethodz** [comment]
Yes. One other thing I noticed is it WILL play movies I previously played
before but only those. I will record a video of this.

**Comment by katsiris** [comment]
I'm new to this and also having the "playing videos is not supported on this device" response when using the correct syntax outlined above. On the lambda console, I get the following:

START RequestId: bd2b1e79-e831-11e6-b516-ad1ede9dd614 Version: $LATEST
Handler 'lambda_handler' missing on module 'wsgi': 'module' object has no attribute 'lambda_handler'
END RequestId: bd2b1e79-e831-11e6-b516-ad1ede9dd614

And when I ask to play music "Tell Kodi to play the album Teenager of the Year", it plays me a sample of what I ask for on the Echo from Amazon Music instead of the Kodi. I also get "there was a problem with the selected skill's response" message if I ask what flim is currently playing, for example. 

In the Alexa app, the error I see is: Skill response was marked as failure; Kodi; Request identifier amzn1.echo.api.... 
The target lambda application returned a failure response. 

I did not do the 'docker' section in the walkthrough, so maybe it's related? The last python script I ran was deploy-to-lambda.py. Not sure if there's another script required to be running/executing?

Sorry, lots of questions. I'm attacking from many different angles but lost at the moment.

**Comment by m0ngr31** [comment]
Still happening to me

**Comment by jingai** [comment]
I... have no idea what's different with my installation then.  It's still working just fine for me :/

**Comment by m0ngr31** [comment]
What invocation name are you using @redlikemethodz?

Switching `cody` -> `kodi` solved the issue for me.

**Comment by jingai** [comment]
Is anyone still having this problem?
