### ISSUE TITLE
Websockets instead of port forwarding?

### ISSUE THREAD

**Issue by quaec** [m0ngr31/kodi-alexa#104]
Would it maybe be a good idea to use websockets or something similar to connect kodi to the (aws) web server that hosts the skill instead of using port forwarding? 

So you wouldn't need to forward a port to the kodi device and instead the kodi device opens a websocket connection to the skill server. I think that would be a more secure way to handle things, since it's probably not the best idea to open a port to your kodi installation or some other web service at home.

I've found another project that seems to do that, but it has been abandoned: https://github.com/rsummers618/HTPC_Alexa_Skill

What do you think? Any caveats that I heaven't thought of?

**Comment by jingai** [comment]
Those that have been concerned with it are using an HTTPS proxy to secure it.  It's not too difficult to set up if you wanted to go that route.

**Comment by quaec** [comment]
I've setup kodi-alexa on the same pc where kodi runs. I've configured apache on my kodi pc to serve kodi-alexa via mod_wsgi and HTTPS where the skill connects to.

Did you mean something like that or is the mentioned HTTPS proxy something different?

**Comment by jingai** [comment]
If you've done that, there's no port forwarding involved besides 443 for Apache.  I do the same thing with my installation.  Provided you've properly secured Apache, there shouldn't be any issues doing it that way, and since the authentication with Kodi is contained on your LAN, your password wouldn't be exposed either.

I was referring to those using a cloud deployment of the skill, who could use an HTTPS proxy just so the password to Kodi isn't sent plaintext.
