### ISSUE TITLE
Intents File - Missing Intents?

### ISSUE THREAD

**Issue by ghost** [m0ngr31/kodi-alexa#11]
Trying to set this up and receiving the following error:

Error: There was a problem with your request: The intent 'DoSearch' was not found in the domain definition. Occurred in sample 'DoSearch search for {Artist}' on line 203.

**Comment by m0ngr31** [comment]
I'll get this fixed tonight. Sorry about that.

**Comment by ghost** [comment]
No problem! Thanks for the awesome work on this, really appreciate it. Your instructions were nice and easy to follow.

**Comment by samabsalom** [comment]
just as appreciative ! 

getting this error
 Error: There was a problem with your request: Unknown slot type 'MUSICARTISTS' for slot 'Artist' 

i add MUSICARTISTS as a slot type as well as MUSICPLAYLISTS
and then i get the above error

**Comment by jingai** [comment]
You need to add the MUSICARTISTS slot type.  Previously, it was called MUSIC, but since I added support for playlists, it made sense to make it more descriptive and make room for other music slot types, too.

If you already had a MUSIC slot type, just make a new one with the same contents called MUSICARTISTS and delete the old MUSIC slot type.  You will also need to add a MUSICPLAYLISTS slot type and populate it with your playlists (kodi-slot-generator has been updated to add these).

**Comment by samabsalom** [comment]
Thats great ! thanks for your help. Added those slot types and ended up deleting the dosearch from the list and it solved the problem.

**Comment by m0ngr31** [comment]
Should be fixed now.

**Comment by jingai** [comment]
Wait.. what commit fixed the missing DoSearch intent?

**Comment by ghost** [comment]
Gonna go ahead and say it's the one that's marked as adding the DoSearch intent ;)

https://github.com/m0ngr31/kodi-alexa/commit/d92652f459862c6625c91e520805b86eac1d074d

@m0ngr31 - Confirmed fixed and working! Thank you so much for the quick turnaround.

**Comment by jingai** [comment]
haha sorry, I guess I checked too soon.
