### ISSUE TITLE
wsgi.py: artists = kodi.GetMusicArtists() did not return on long request

### ISSUE THREAD

**Issue by stefanbode** [m0ngr31/kodi-alexa#111]
my 800k result seems to stop this from working. Last lines are:

,{"artist":"Richard Wagner","artistid":15266,"label":"Richard Wagner"},
{"artist":"Randy Kaplan","artistid":15356,"label":"Randy Kaplan"}],
"limits":{"end":12358,"start":0,"total":12358}}}

I try to increase mem to 265Mb. Still timeout after 60 seconds. AWS Messages from 128MB test are:

15:01:36 Sending request to http://xxxx.homeserver.com:yyyy/jsonrpc
15:01:36 JSON Request {"jsonrpc": "2.0", "method": "AudioLibrary.GetArtists", "id": 1}
JSON Request
{
    "jsonrpc": "2.0",
    "method": "AudioLibrary.GetArtists",
    "id": 1
}
15:02:36 END RequestId: 7ae0ad84-f2c6-11e6-8906-97431fdb464a
15:02:36 REPORT RequestId: 7ae0ad84-f2c6-11e6-8906-97431fdb464a	Duration: 60001.89 ms	Billed Duration: 60000 ms Memory Size: 128 MB	Max 

If we cannot fix it we should use the limit in the JSON to avoid breakdown.

**Comment by jingai** [comment]
How on earth do you have 12000 *artists*?!  o.O

**Comment by stefanbode** [comment]
If you have a large CD-Collection with a lot of samplers and grab them....
Do you have any short workaround, or just wait for the next release? I was assuming that you can send "complex" searched like "albums where artist == xxx" direct to kodi without that workaround. Also the slot type list is not really working on that size, but the fallback to ask kodi if the result is empty is working fine. Therefore no problem here. My video list is quite short. Haha. No issues there.

**Comment by jingai** [comment]
Related to #79.

**Comment by stefanbode** [comment]
Hi jingai. I think this is only partially related to #79 because in case #111, KODI is capable of responding with the right answer in a very quick time. Therefore the problem is only on the skill side.

**Comment by jingai** [comment]
I didn't say it was a duplicate -- just related.

**Comment by jingai** [comment]
> I was assuming that you can send "complex" searched like "albums where artist == xxx" direct to kodi without that workaround.

The problem is we don't yet know what the artist is at this point.  We need the full list of artists to get a match to what was heard.

If it takes a long time to retrieve this list, it's going to time out on the client-side (your Echo device) no matter what we do.

I think the way to solve this will probably be by caching the library in some way, so we only have to ask Kodi for the library information if something has changed since the last time we asked.

**Comment by jingai** [comment]
For reference, I don't encounter this issue here hosting the skill locally.  This isn't to suggest that hosting it locally is the fix, just noting that it's purely an issue of the request taking too long.

I think caching the responses from Kodi is really the only way we can make this work for cloud deployments.

**Comment by jingai** [comment]
There isn't really anything we can do to fix this with the skill as it is.  We've explored numerous other possibilities, but the only way we can really handle this is to make another skill using the Video Skill API.
