### ISSUE TITLE
Suggestion: Support Music Videos

### ISSUE THREAD

**Issue by ScriptSorcererUK** [m0ngr31/kodi-alexa#118]
It would be great if we could have similar support for music videos as we currently do for music, so we can ask kodi to play specific a specific music video track by a specific artist or all music videos by a specific artist. I don't know how much work this would be, it would require two new slots adding, but hopefully a lot of the groundwork would already have been done and the music code can be copied and edited to implement this.

Thanks very much.

**Comment by jingai** [comment]
I want this too, but it's actually significantly more work than it seems at first.  To do it completely, there's a whole lot of overlapping phrases for one thing -- all of the existing methods for music (audio) would need to be duplicated for music (video).  The duplication/refactoring in the code is one thing, but distinguishing the utterances from each other is another (bigger) thing.

FWIW, I get around this currently with video playlists.  I'm not saying this is an answer to your Issue, but it's a decent workaround in the interim.

**Comment by jingai** [comment]
As much as I really want this, we're having troubles saving the skill as it is, due to its size.  Since this would effectively mean duplicating nearly all of the music intents, I don't think we can support it.

Perhaps after #82 ...

**Comment by jingai** [comment]
Oh, I just had a thought!

Perhaps instead of making a whole new set of intents and utterances, we can just make all of the existing music intents also search music videos.

So, if a music video is found that matches the song requested, it can just prefer that to the audio-only version.

If it's a request for all music by an Artist, we could add both songs and music videos to the playlist (I think -- I know mixed playlists are supported, but I need to see if we can do this via JSON-RPC).

If the request is `listen to` as opposed to `play`, perhaps it should force the audio-only version.

Thoughts?

**Comment by jingai** [comment]
Of course there's no link between music and music videos for artists.. sigh.. means we'd have to match twice, which means requesting the artist list for music videos too :(

I suppose if we implement it this way, it'd need to be a configurable option at least.  Though, I imagine the request for music video artists would be small enough for everyone except those that actually want this anyway... hmm..

**Comment by jingai** [comment]
Addressing this in #210

**Comment by jingai** [comment]
The majority of this will be handled by PR #210 and the rest by Issue #212.
