### ISSUE TITLE
WSGI: Store configuration in file

### ISSUE THREAD

**Issue by jingai** [m0ngr31/kodi-alexa#21]
Instead of environment variables.

I have code for this already, but I need to make it generic.

**Comment by m0ngr31** [comment]
Can you update the main readme to show how to get a wsgi server running?

**Comment by jingai** [comment]
Sure can, but I'm about to run from a hurricane, so it may take me a little bit lol.

**Comment by m0ngr31** [comment]
No worries

**Comment by jingai** [comment]
Regarding documentation, I'm not sure what the scope should be honestly.

Heroku uses WSGI, doesn't it?  I think that or something like it is what most will use, and you've documented that already.

For a self-hosted server, it depends on the web server the user chooses.. most are apache I'd guess, but it's enough to say, "use mod_wsgi" in that case, I think.  After all, if they can set up apache, they probably know that already?

**Comment by digiltd** [comment]
> if they can set up apache, they probably know that already?

They might, but given the universal appeal of what this skill gives you and the popularity of Kodi, I expect many will be messing about without really knowing what they are doing. What are the numbers looking like for the traffic on this repo?

@m0ngr31 would you might turning on the wiki functionality for this repo?

**Comment by Xaelias** [comment]
`they can set up apache, they probably know that already?`
Yes and know. I have an apache server running on a couple hosts because it comes with other services, or because I set it up to host a small static website. And clearly I have no idea what you just said :-)

You can never over explain something. You don't know who is going to come and use your tool. It does not hurt to explain something that might be obvious. Worst case scenario, people will skip that part.

**Comment by jingai** [comment]
I mean that if someone doesn't know what they're doing, they're better off using one of the other solutions like Heroku or Lambda.  Hosting it yourself without general knowledge is dangerous, honestly.

**Comment by Xaelias** [comment]
But what if somebody wants to learn?

**Comment by jingai** [comment]
I get that, but that's why I asked what the scope is.  There is already plenty of documentation for setting up mod_wsgi out there.  How in-depth should we go for a README on an Alexa skill?

The WSGI handler is already documented here for Heroku.  From the standpoint of the skill, that's what you need to do for any other web server as well.

If I document here how to set up Apache from scratch, do I include nginx as well?  IIS?  Do I include how to properly load certs?

**Comment by Xaelias** [comment]
If you know of good documentation, maybe just quote a couple links? I agree we can't explain everything, everywhere, all the time.
You obviously know more about these subjects that I do. So I'll honestly just trust you on this.

But I think if we can at least provide a couple links in the doc, so that if people want to try to set this up, at least they are not left alone to search Google and StackOverflow on their own. My .02 :-)

**Comment by jingai** [comment]
Is there a particular aspect that you find confusing?

It'd probably be best if you create another Issue detailing what you think needs to be improved regarding the documentation.
