### ISSUE TITLE
trakt 

### ISSUE THREAD

**Issue by crowland88** [m0ngr31/kodi-alexa#23]
sorry to write this here, but is there any way to add trakt to this skill, so trakt works the same as if it was plaing a movie/tv show from the library ?
just in case some one library is messed up ?

**Comment by m0ngr31** [comment]
I'm not sure I understand. Have Trakt play something instead of the library?

**Comment by crowland88** [comment]
Please have a look here.
http://koditips.com/why-trakt-is-better-than-kodi-library-integration/

**Comment by jingai** [comment]
No real comment on adding the feature, but if Kodi did move from library to Trakt as is suggested in that 'article,' I'd be moving away from Kodi... I see no evidence that that is the case though.

**Comment by digiltd** [comment]
If you have the Trakt addon already scrobbling your library, when controlling Kodi with this Skill you are still using Kodi as normal and I confirm Trakt works fine.

I think you are talking about controlling a video addon that uses Trakt as a way to browse content and then attempt to stream it. Trakt in itself is just a way of keeping track of what you watch, it is not a way of delivering content.

Your question does highlight a perfect example of why Trakt is not better than Kodi library integration :)

Some addons integrate the strm files into the Kodi library with some level of success, but many of the dedicated streaming addons rely on you wading through menu after menu in order to find stuff.

**Comment by jingai** [comment]
> I think you are talking about controlling a video addon that uses Trakt as a way to browse content and then attempt to stream it.

I think this is it, yeah.  I get weird requests like this for skin.metropolis too and I'm always confused until I go searching outside the kodi forums/wiki.. e.g., stuff not condoned by Team Kodi..

**Comment by crowland88** [comment]
I think this is it, yeah. I get weird requests like this for skin.metropolis too and I'm always confused until I go searching outside the kodi forums/wiki.. e.g., stuff not condoned by Team Kodi..

Yeah sorry that's what I was trying to say, I understand if you don't wish to add this.
Add-on like exodus and salt use a trakt account to search for the links. A few skins have trakt integrated so u can enter the TV show or movie trakt folder in 1 click from the kodi home screen or you can add trakt folders ( tv shows) to a sub menu like in aeon-mq 

But what would be great is to use trakt my calendar as found in Salt so you can find out all TV shows that have recently been on overnight.

**Comment by jingai** [comment]
I'm going to add the ability to open (and hopefully manipulate, to some extent) addons soon.  This could enable the TV Show last aired status functionality you're wanting.

However, and I don't speak for @m0ngr31, but I personally won't add anything to support piracy.

**Comment by crowland88** [comment]
that great thank you this may help you.
http://docs.trakt.apiary.io

**Comment by jingai** [comment]
The interaction with Kodi will be limited to what Kodi exposes via the JSON RPC interface.  The skill wouldn't be directly talking to Trakt, nor would it really know what Trakt even is.

It would be possible to add more support for specific addons, but going down that road is a maintenance nightmare, since interfaces for addons are a lot more flexible (read: change a lot more often) and not in any way standardized.  I don't know if @m0ngr31 has any intention to go that route, but I'm inclined not to, simply because I don't want to maintain it.

I get requests like this for skin.metropolis a lot too and have experience trying to keep up with it.  I've decided in the end (with regard to my skin) to only support certain addons that have a) solid developers that care to include feedback from the skinners they're supporting, b) reasonably well thought out APIs, c) have a huge user base which helps them achieve a greater lifespan.

The above could very well include the Trakt addon; however, it's not yet certain that we want to go down that road at all for the skill.  That'd be a whole other discussion.

**Comment by digiltd** [comment]
If the addon integrates with the library then it would work fine using this skill. 

The official Trakt addon (from the Kodi repository) just sits in the background marking episodes as watched and keeping them in sync with the site (https://blog.trakt.tv/kodi-scrobbler-sync-plugin-1f148b5070a5#.bb3b7a53v) 

For what @crowland88 is talking about would require integrating each specific streaming addon, the addon would talk to Trakt itself. But as you say, those types of addons come and go all the time, the maintenance would be a nightmare.

**Comment by jingai** [comment]
Yeah, sorry, I just kind of went with the assumption that he was referring to integration with specific addons, since, as you said, it would otherwise 'just work' if it were just the Kodi library.

More specifically, he was talking about stuff like Exodus initially.. which I won't even bother looking into.

For the TV Guide-like functionality, I can guess the Trakt addon might have a function to present that.  There are a few addons that do this.  Provided the default open action is this, when I add support for opening addons, you'd automagically get this feature.

I could also extend it to open favorite links, which would give you the ability to navigate anywhere within an addon by voice.  It'd be a bit cumbersome (to set up, not to use), but honestly it's not much different than the way Kodi Skins handle custom furniture anyway, so it'd at least be familiar.

**Comment by crowland88** [comment]
its ok, It was a bad idea, but adding stuff to the favourites would be nice for ustvnow and ontap tv guide addons.
it looks like something is on the way https://www.facebook.com/trakt.tv/videos/1195106010527702/ its a shame it not intergraded with your addon.

**Comment by jingai** [comment]
> it looks like something is on the way https://www.facebook.com/trakt.tv/videos/1195106010527702/ its a shame it not intergraded with your addon.

It's still not clear exactly what you think should be integrated with this skill...?

**Comment by m0ngr31** [comment]
Yeah, I'm pretty confused by the intended functionality requested here.

**Comment by michaelhinchey** [comment]
So if I understand this thread, this will only really work for hardcopy files that exist on your computer or somewhere stored?  This will not work for add ons like exodus or even the amazon prime or Netflix add on.    If someone can confirm that would be great.  Thx 
    Is there a way outside of kodi to Control Netflix directly from the web or Windows app? 
   Is there away to control kodi from Alexa

**Comment by jingai** [comment]
http://forum.kodi.tv/showthread.php?tid=254502&pid=2443174#pid2443174

> Is there away to control kodi from Alexa

That's literally the purpose of this skill...

**Comment by jingai** [comment]
Closing this as I don't think there's anything to actually do here.
