### ISSUE TITLE
Custom Alexa skills in more than one Echo devices

### ISSUE THREAD

**Issue by VasMan** [m0ngr31/kodi-alexa#230]
Hi,

Has anyone managed to make any custom Alexa skills (e.g. Google Assistant, or Kodi) run in more than one Echo devices registered under same Amazon account and located in the same address/home/wifi? When I created the custom skills (Google assistant & Kodi) I had only one Echo device and it worked (and still does) fine. However, the second Echo device I bought, registered under the same Amazon account, does not recognise the custom skills, the second device does recognise though all the official skills (harmony, hue lights etc.) I use on my first one. De-register/re-register of the Echo device or multi-room/group configuration of the two Echo devices did not fix it, any ideas?

Many Thanks for any guidance and feedback

**Comment by jingai** [comment]
Yes, I have 8 Alexa devices and two Amazon accounts in a household, with one copy of the skill per account, and it works on all of them.

The likely problem is that you're not logging into the second Echo with the same account you use on the other Echo (and development account).  Otherwise, try disabling and re-enabling the skill on the developer page.. I've never had to, but it's worth a try.

In the future, please post questions such as these on the [forum](https://forum.kodi.tv/showthread.php?tid=254502).  GitHub is for bugs, feature requests, etc, as the README states.

**Comment by VasMan** [comment]
Hi,

Thanks for the help and sorry for posting this as a bug. Btw my issue was
fixed after I added UK English language in all of my custom skills (per
skill configuration). The reason being that first echo device was
registered with my Amazon US account which then got migrated to a UK
account but still worked fine with US language on the skills, second echo
device (that was not working) was registered directly to the Amazon account
that is UK now.

Now I need to figure out why the kodi-alexa skill does not find all songs
in my library and probably does not dynamically update the contents of the
library, will post this on the forum you pointed

Thanks so much for the prompt response and support

Vasilis
