### ISSUE TITLE
Resume episode / movie

### ISSUE THREAD

**Issue by willhowlett** [m0ngr31/kodi-alexa#246]
It would be handy to be able to resume an episode or movie that you are in the middle of watching

e.g.

Ask kodi to resume ...
Ask kodi to continue playing ...

It could also be handy if the skill were able to detect if media was already in progress, and to ask if you wanted to resume or start from the beginning if you ask it to play it (though I recognise that may be more complicated to implement)

**Comment by jingai** [comment]
It actually already does attempt to resume currently with the play/watch command.  We also have an intent for "Continue playing last show," which would continue the last show you watched where you left off.

Adding `resume` as a keyword here could be possible.  It would be a synonym for `play` or `watch` in the event that you asked for something that doesn't have a resume point, but that's probably OK.  The only real problem here that might arise is potential conflict with the built-in action for resume, as it can (and currently only does) mean 'resume from paused state' as well.

Asking for voice confirmation could work, though as I said above, it already does attempt to resume by default.  I currently just tell it to start over if that's what I wanted instead.

**Comment by jingai** [comment]
Going to close this since honestly the functionality is already there, and the extra verbiage would probably just confuse things.
