### ISSUE TITLE
AWS lambda-deploy error

### ISSUE THREAD

**Issue by irvingwa** [m0ngr31/kodi-alexa#33]
I set all my variables in my .env file but when I run lambda-deploy deploy I get the following error:

botocore.exceptions.NoRegionError: You must specify a region.

**Comment by m0ngr31** [comment]
What does your .env file look like?

**Comment by irvingwa** [comment]
KODI_ADDRESS = < MYIP >
KODI_PORT = 8081
KODI_USERNAME = kodi
KODI_PASSWORD =
LAMBDA_ENV_VARS = KODI_PASSWORD,KODI_USERNAME,KODI_PORT,KODI_ADDRESS

REGION = us-east-1
LAMBDA_TIMEOUT = 60
LAMBDA_MEMORY_SIZE = 128
LAMBDA_HANDLER = wsgi.lambda_handler

AWS_ACCESS_KEY_ID = < MYKEY >
AWS_SECRET_ACCESS_KEY = < MYSECRET >
LAMBDA_ROLE = < MYROLE >

**Comment by jingai** [comment]
Somebody else on the Kodi forums stated that they had to change the region in the AWS CLI to fix this: http://forum.kodi.tv/showthread.php?tid=254502&pid=2438097#pid2438097

**Comment by digiltd** [comment]
I had the same problem and initially I solved it by installing and configuring the [AWS CLI](https://aws.amazon.com/cli/)

But you might not need to do that as I just tried adding `AWS_DEFAULT_REGION` to the .env file and that also worked. 

```
AWS_DEFAULT_REGION = eu-west-1
```

@m0ngr31 I don't know if `REGION` is referenced somewhere else or if it is a typo/bug which went unnoticed because you already had the AWSCLI configured on your machine. But I left that var as is just in case.

**Comment by irvingwa** [comment]
@digiltd the AWS_DEFAULT_REGION fixed the issue thanks!

**Comment by jingai** [comment]
8b8e0eb2f7c86892250cf737ff03b6386c7c4836 should take care of this.

**Comment by irvingwa** [comment]
Sorry didnt know you were gonna update this tried to save you some time with the PR. @jingai

**Comment by jingai** [comment]
No need for an apology, it was appreciated :)  I just squashed it into one commit is all.

**Comment by jingai** [comment]
I'll let @m0ngr31 close this and PR #34 on the off-chance that it breaks something for his deployment.
