### ISSUE TITLE
ValueError: No JSON object could be decoded.

### ISSUE THREAD

**Issue by irthomasthomas** [m0ngr31/kodi-alexa#38]
Hi, great looking project. I've just installed kodi and kodi-alexa clean today on ubuntu. When I try to do kodi.GetMovie() or anything similar I get the error "No JSON object could be detected". As such I haven't been able to generate the slot values for the skill yet. Any ideas?

**Comment by jingai** [comment]
You need to get the slot generator working before anything will work.

But otherwise, post kodi.log (with debugging enabled) and your relevant web server logs.  Be sure to scrub out IPs/passwords to keep them private.

edit: I mean the slots have to be present at least.  It might/probably will work if they're just empty, though.

**Comment by jingai** [comment]
Please post your question over here: http://forum.kodi.tv/showthread.php?tid=254502

Since I doubt this is an issue with the code, I'm closing this here, but we can help you on the forums.
