### ISSUE TITLE
i18n (Internationalisation)

### ISSUE THREAD

**Issue by danielmasur** [m0ngr31/kodi-alexa#44]
Amazon Echo is going on sale on the 26th of october.
I'm already on translation the utterances files and will open a PR once I have the Echo and got it testing.

But I bet theres a whole lot to do about exporting all of Alexas responses into a seperate file rather than having them hard coded in the main wsgi.py file.
I'm nowhere near capable of doing this change or suggest any way to program this, but I will be able to translate Alexas responses into German.

I'm attaching Amazon provided documentation on this Topic:
- https://developer.amazon.com/public/community/post/Tx2XUAQ741IYQI4/How-to-Build-a-Multi-Language-Alexa-Skill
- https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/developing-skills-in-multiple-languages

**Comment by danielmasur** [comment]
I had a look at these docs but also had a look at python and i18n in general. Does anything speak against using python gettext and .pot .po and .mo files like outlined here https://wiki.maemo.org/Internationalize_a_Python_application ? I'm willing to have a go at this but admittedly aren't a highly skilled programmer, so could do with some starting points.

**Comment by jingai** [comment]
I haven't commented on this not because I don't think it's worthwhile, but simply because I haven't had the time/energy/desire yet to tackle thinking it through.  Internationalization is one of those problems that's always bigger than it appears at first, so I want to set aside time to get it right.

**Comment by danielmasur** [comment]
I've been having a go at this using standard python gettext and _() mechanism.
Please have a look at this commit and leave comments.
[Initial Release of i18n using gettext](https://github.com/ausweider/kodi-alexa/commit/03e131329ea85700baf7ecda45a9039a5da09d2d)

I've been using this with what I would call great success over the weekend.

**Comment by jingai** [comment]
That's essentially how to go about it, yes.

My primary concern is maintenance of it all.  With separate utterance files and response files for every language, it adds a fair amount of extra effort (namely testing) for each new command added, changed, etc.

I'm OK with this personally if we just determine that new features are added with English first and other languages are allowed to lag behind.  By that, I mean if I add a new command, I will only make the changes for the English language files and will not wait for other languages to catch up before release of the feature.  I would expect that if someone cares about the other languages that they will step up with a catch-up PR.

This means that for a period, small or large, there would not be feature parity amongst the different languages.  Which will probably mean forum posts to reply to, but the only way to get around it would be to hold all PRs until contributors show up with translations.

In the long-term, something like Transifex could really help here.. but given that this is purely hobby for me, I don't really want to be the guy that sets all that up and maintains it.. I already spend more time fiddling with my home automation systems than enjoying them, much to my family's chagrin ;)

One other thing:  could you please make a branch with the changes instead of adding them to master?  When I get around to looking it over I'd just pull your branch down.

**Comment by danielmasur** [comment]
Maintenance for i18n will always be a pain I do realise, but, oooh, it adds so much feel :) Me I wouldn't talk English in my home, and I'm sure the french wont either once they get their Alexa.

When it comes to translating new strings I also had to do "in between merges" from upstream and then continue, so I would expect this to be normal for a project this size. I've not looked at transiflex, but thought it to be "not free", as in money.

As for German translations, I'm willing to do the translation duties for a fair time to come. I guess this skill is a hobby thing for all the current devs working on it right? Me too I have to worry about https://en.wikipedia.org/wiki/Wife_acceptance_factor , which means that native language is an absolute must have. :D

I've setup a new branch.
https://github.com/ausweider/kodi-alexa/tree/i18n
I haven't done a PR on purpose as, even with limited skills, I do realise that "those two globals" will put a few devs off of this. Anyway, I'm pleased about how this is progressing.

**Comment by jingai** [comment]
It's not really a question of whether it will happen -- it will.  The questions are:
1. Who will maintain what?
2. Do current developers have time for this right now?  If not, does anyone else?

As you suggested, yes, this is just a hobby project for us.  I don't mind doing the review and pulling this in, but a big part of a PR is dealing with the aftermath.  It will undoubtedly generate support requests.  So, if I'm the one doing the review and merge, I'd really like to wait until I have some free time to allocate to it.

At a glance, one thing I don't like (but still might be the best way to handle it) is using the English strings as IDs for the actual strings.  It's more legible when browsing the code (vs say, giving them numeric IDs), but it means changes in two places.

Granted, you _could_ only make the change in the translation files, but eventually the string IDs in the sources might not match those in the translation files, which I think will end up being confusing.  Particularly if the change is the exact opposite of the original ("Ok, sure I can do that" -> "Sorry, I can't do that", for instance).  I'd avoid doing that, but I'm just trying to illustrate the point.

**Comment by m0ngr31** [comment]
@ausweider: I'm wondering if you can help with the translation for v2.5. It's on the flask-ask branch. I did some Google translate for the card and voice responses, but I'm sure it's trash. If it's okay with you, I'd like to use some of your utterances as well. But I'll need more translations too if you're up for it.

**Comment by danielmasur** [comment]
Sure. See #96

**Comment by m0ngr31** [comment]
Thanks for doing that so quickly! I merged it into my branch and it will be merged to master soon.
