### ISSUE TITLE
Subtitles can be enabled/disabled but not downloaded

### ISSUE THREAD

**Issue by x5nder** [m0ngr31/kodi-alexa#49]
Don't know where to suggest this, so I hope it's okay I'm posting it here:

I am missing the option to download a subtitle. If I'm not mistaken, the code would be:

def SubtitlesGet():
  playerid = GetVideoPlayerID()
  if playerid:
    return SendCommand(RPCString("GUI.ActivateWindow", {"window":"subtitlesearch"}))

with alexa.intents:
    {
      "intent": "SubtitlesGet",
      "slots": []
    },

and alexa.utterances:
SubtitlesGet download subtitles
SubtitlesGet get subtitles
SubtitlesGet find subtitles

(Since I have no GitHub experience, I am definitely not trying to implement this myself, haha)

**Comment by jingai** [comment]
Thanks for the examples.  I'll have a look at this probably this weekend.

**Comment by m0ngr31** [comment]
I have this added, but it doesn't show anything for me. I don't use subtitles, so I'm guessing I need to do some setup to enable the search to show up?

**Comment by jingai** [comment]
Can you activate the subtitle search in Kodi using remote/keyboard?

**Comment by fonzie24** [comment]
There is no specific shortcut key to open the subtitle search that I am aware of.  However, you can customize the keymap to create the shortcut.

"subtitlesearch" Window ID is 10153 and it points to the dialoguesubtitles.xml

http://kodi.wiki/view/keymap

**Comment by jingai** [comment]
I'm kind of inclined to say this is out of scope for the Alexa skill.  It requires a lot of interaction after invoking that honestly is best handled with a remote/keyboard/mouse.

It would be possible to just download the first available via voice, but it's probably not likely to be what the user wanted.  Unsure, honestly..

**Comment by jingai** [comment]
I'm inclined to think that for a VUI, it should just download the first hit for the user's locale rather than popping a dialog for choosing what to download.

But I'd like some input from others on this before I tackle the problem.

**Comment by fonzie24** [comment]
Yes, I'd be fine with it downloading the first subtitle file from the list of the subtitle provider that you have set as default.

**Comment by jingai** [comment]
I'll probably push forward with that then and see if there are any complaints.

**Comment by fonzie24** [comment]
sounds good. thanks for keeping us updated.

**Comment by jingai** [comment]
Just curious, but what's wrong with letting Kodi just auto-download the first available subtitle for your language for this?

In Kodi, if you go to Settings->Player->Language/Download Services, you can select the option to automatically download the first available subtitles there.  Then you can use the already-existing commands in the skill to enable/switch/etc subtitles.

Is there some reason this doesn't work for you?

I think this is probably the right way to go, honestly, especially since there is no existing JSON-RPC for downloading subtitles.

**Comment by fonzie24** [comment]
Honestly, this isn't really a necessity. It was more of a "can it be done? " without really asking "should it be done?" as Dr. Malcolm so eloquently put it in Jurassic Park. 

Its fine to just leave this feature out.

**Comment by jingai** [comment]
I don't mind leaving the Issue open, it's just that the way I was thinking of implementing it currently isn't possible.

The only way atm is what you suggested, which is why I was wondering if you'd seen the auto-download feature.

**Comment by fonzie24** [comment]
Yes, I had seen that.  For me it isn't necessary to set it up because I use Emby as the backend and I already have it set to download subtitles for everything automatically.

This was more geared towards downloading the correct subtitles for video files that had subtitles that were out of sync.

What would be kind of cool, now that I think of it, would be to give a command and have it download the first set of subtitles on the list. Then, if the command is uttered again, it'll download the following subtitles on the list and replace the previous ones.  This would allow you to find the properly synced subtitles while watching a movie uninterrupted.

**Comment by jingai** [comment]
Problem is, I don't see a JSON call to do what you're suggesting.

It might be possible to call the subtitle service addon directly, but this would depend on all subtitle services sharing a common directory structure (honestly not sure if they do).  There are currently 30 of these services in the official repository, so if they don't adhere to one spec, it would be troublesome to support.

I don't think I'd personally ever use this, since it would be infinitely easier to navigate with a remote.. but if it's possible, it's worth investigating.
