### ISSUE TITLE
CurrentPlayItemTimeRemaining and local time

### ISSUE THREAD

**Issue by jingai** [m0ngr31/kodi-alexa#64]
The CurrentPlayItemTimeRemaining intent will return the time at which the currently playing item will end relative to local time on the server.  This works out if the server is located in the same time zone as the Kodi installation, but for cloud deployments of the skill this probably is often not the case.

I couldn't find a way to get at the time zone information of the Echo device from which the request originated, so my initial thought was to make an environment variable in which the user could specify his/her time zone.

Raising this as an issue to see if anyone has any better ideas, though.

It might also be the case that Heroku/Lambda/etc have a built-in mechanism for setting the time zone?

**Comment by digiltd** [comment]
The request from Alexa contains locale and timestamp.

adding 

``` python
  appLocale = event['request']['locale']
  appTimestamp = event['request']['timestamp']

  print("lambda_handler: appLocale=" + appLocale)
  print("lambda_handler: appTimestamp=" + appTimestamp)
```

gave me this

```
lambda_handler: appLocale=en-GB
lambda_handler: appTimestamp=2016-11-16T09:33:45Z
```

The timestamp looked interesting, I am not sure where that comes from. I am in UK and the Skill/Lambda are in eu-west-1 (Ireland) so they would be on my timezone already. As German Skills also have to use Ireland and US have to use us-east-1 then this probably wouldn't be a reliable way to get the local timezone.

But it might be worth testing at your end.

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/developing-an-alexa-skill-as-a-web-service#checking-the-timestamp-of-the-request

Or to save over complicating it, a simple env var for a user to set their GMT offset would be enough to do the trick.

Though for me I don't really find myself needing to know how much longer something is on for. If i start a movie I would already have an idea how long it is and make the "do I have time?" decision at that point. Thinking more about it, if I did need to know (perhaps it is getting too late, or I have something I needed to do) then "there are 40 minutes left" would be enough information for me to look at the clock and decide.

But everyone's need is different and I guess because you are implementing the function that it is something you would use :)

**Comment by jingai** [comment]
I don't use it either, but I got enough requests for it in skin.metropolis that I figured I'd nip it in the bud here. 

The timestamp provided in the request is UTC and the locale is just for language.  Here, I get 'en-US', which obviously isn't narrow enough to get the user's local time.

So, unless someone has any other ideas, I think we'll have to use an environment variable for the user to set timezone/offset.

**Comment by jingai** [comment]
Would someone mind testing https://github.com/jingai/kodi-alexa/tree/localtime ?

Please test with SKILL_TZ as empty, undefined, and whatever time zones you'd like to test.

Note that I have not had a chance to try the code at all, so if it just out-right fails, let me know.
