### ISSUE TITLE
Kodi SLOTS

### ISSUE THREAD

**Issue by karl0ss** [m0ngr31/kodi-alexa#70]
I want to ask a question, so I see that the SHOWS slot has my tvshow names in it...

If I have added a new show to my kodi, do I need to add the show name to SHOWS slot? or will something update itself at some point?

Thanks

**Comment by jingai** [comment]
You only need to add new media to the Slots if the skill is having trouble determining what you're asking for.

**Comment by Xaelias** [comment]
What jingai said.
The slots need some base values to help Amazon understand what kind of value it should expect. Obviously if the name of the show is in there, it's very likely your echo will understand it perfectly everytime. If you have multiple shows with very similar names (walking dead vs talking dead, random example), you might want to update your slot values.
Otherwise you can just leave them alone :-)

**Comment by karl0ss** [comment]
Ok great, this is such a good system :)

Is there a command I can issue to tell me "new episodes added today?" As this would be really useful..

**Comment by jingai** [comment]
> Is there a command I can issue to tell me "new episodes added today?" As this would be really useful..

Not currently, though it'd be possible.  You can open a new Issue requesting this feature.

Also, the Issues here on github are not really for troubleshooting/help.  You should only open an Issue here on github if you:

1. think you found a bug,
2. want to request a new feature.

If you think 1 applies, but you're not sure, please post [on the forums](http://forum.kodi.tv/showthread.php?tid=254502) first.  Same applies if you just have a question for us.
