### ISSUE TITLE
Deploying to Lambda using a Raspberry Pi

### ISSUE THREAD

**Issue by fergalom** [m0ngr31/kodi-alexa#81]
Using a raspberry pi 2, python deploy-to-lambda.py produces a "MemoryError" 

`pi@raspberrypi ~/kodi-alexa $ sudo python deploy-to-lambda.py
2016-12-16 14:37:03:INFO:botocore.credentials: Found credentials in environment variables.
2016-12-16 14:37:04:INFO:lambda_deploy: Packaging lambda kodi-alexa
2016-12-16 14:37:04:WARNING:lambda_deploy: A .env file exists in your Lambda directory - be careful that it does not contain any secrets you don't want uploaded to AWS!
2016-12-16 14:37:04:WARNING:lambda_deploy: Skipping inclusion of of .env file - use LAMBDA_ENV_VARS instead (see documentation for more information)
2016-12-16 14:38:43:INFO:botocore.vendored.requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): lambda.us-east-1.amazonaws.com
2016-12-16 14:38:44:INFO:lambda_deploy: Adding new kodi-alexa lambda
Traceback (most recent call last):
  File "/usr/local/bin/lambda-deploy", line 9, in <module>
    load_entry_point('lambda-deploy==0.1.2', 'console_scripts', 'lambda-deploy')()
  File "/usr/local/lib/python2.7/dist-packages/lambda_deploy/lambda_deploy.py", line 376, in main
    method()
  File "/usr/local/lib/python2.7/dist-packages/lambda_deploy/lambda_deploy.py", line 215, in deploy
    Publish=True
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 513, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 566, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/validate.py", line 272, in serialize_to_request
    operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/serialize.py", line 416, in serialize_to_request
    serialized, shape, shape_members)
  File "/usr/local/lib/python2.7/dist-packages/botocore/serialize.py", line 461, in _serialize_payload
    partitioned['body_kwargs'], shape)
  File "/usr/local/lib/python2.7/dist-packages/botocore/serialize.py", line 527, in _serialize_body_params
    return json.dumps(serialized_body).encode(self.DEFAULT_ENCODING)
MemoryError
Downloading/unpacking requests (from -r /home/pi/kodi-alexa/kodi-alexa/requirements.txt (line 1))
  Running setup.py egg_info for package requests
    warning: no files found matching 'test_requests.py'
Downloading/unpacking gunicorn (from -r /home/pi/kodi-alexa/kodi-alexa/requirements.txt (line 2))
  Running setup.py egg_info for package gunicorn
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
Downloading/unpacking yaep (from -r /home/pi/kodi-alexa/kodi-alexa/requirements.txt (line 3))
  Downloading yaep-0.0.6.tar.gz
  Running setup.py egg_info for package yaep
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
Downloading/unpacking pycountry (from -r /home/pi/kodi-alexa/kodi-alexa/requirements.txt (line 4))
  Running setup.py egg_info for package pycountry
    warning: no previously-included files matching 'src/pycountry' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Downloading/unpacking pytz (from -r /home/pi/kodi-alexa/kodi-alexa/requirements.txt (line 5))
  Running setup.py egg_info for package pytz
Downloading/unpacking fuzzywuzzy (from -r /home/pi/kodi-alexa/kodi-alexa/requirements.txt (line 6))
  Downloading fuzzywuzzy-0.14.0.tar.gz
  Running setup.py egg_info for package fuzzywuzzy
Installing collected packages: requests, gunicorn, yaep, pycountry, pytz, fuzzywuzzy
  Found existing installation: requests 0.12.1
    Uninstalling requests:
      Successfully uninstalled requests
  Running setup.py install for requests
    warning: no files found matching 'test_requests.py'
  Running setup.py install for gunicorn
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    SyntaxError: ('invalid syntax', ('/tmp/tmpzRVaV3/lib/python/gunicorn/workers/_gaiohttp.py', 84, 26, '                yield from self.wsgi.close()\n'))
    Installing gunicorn_paster script to /tmp/tmpzRVaV3/bin
    Installing gunicorn script to /tmp/tmpzRVaV3/bin
    Installing gunicorn_django script to /tmp/tmpzRVaV3/bin
  Found existing installation: yaep 0.0.6
    Uninstalling yaep:
      Successfully uninstalled yaep
  Running setup.py install for yaep
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
  Running setup.py install for pycountry
    warning: no previously-included files matching 'src/pycountry' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
  Running setup.py install for pytz
  Running setup.py install for fuzzywuzzy
Successfully installed requests gunicorn yaep pycountry pytz fuzzywuzzy
Cleaning up...`

This is related to the python deploy-to-lambda.py trying to pip install the requirements in requirements.txt.
Rpi is limited on memory and Pip is trying to read everything into memory before caching it - 
This can be overcome using "pip install <package_name> --no-cache-dir" ?

Reference: http://stackoverflow.com/questions/29466...matplotlib

**Comment by digiltd** [comment]
have you tried not using sudo?

you shouldn't need to run it as root

**Comment by fergalom** [comment]
yes, tried it without sudo first - same result

**Comment by digiltd** [comment]
Not sure what to suggest, is the Pi the only machine available to you to deploy from?

It sounds like it is a problem with [lambda-deploy](https://github.com/jimjkelly/lambda-deploy) rather than the Skill itself.

The purpose of the `deploy-to-lambda.py` script is to copy just the files required by the skill to a seperate folder and then deploy from that folder. This prevents everything being uploaded when you just run `lambda-deploy deploy`.

You can try running `lambda-deploy deploy` from the project folder, but be aware that this will deploy everything in the folder (inc the .git folder, readme, Docker bits etc) to lambda.

I did knock up a [bash script](https://github.com/digiltd/kodi-alexa/blob/package-lambda-script/package-for-lambda.sh) that does the same thing. Though I doubt it will make a difference as both the bash and python scripts do the same thing (copy the essential files to a folder and then run the same deploy script)

**Comment by 40wattrange** [comment]
If you are trying to install it ON the raspberry pi to use locally, try this:

http://forum.kodi.tv/showthread.php?tid=254502&pid=2411411#pid2411411

**Comment by jingai** [comment]
It sounds like he is not trying to install it on the rPi2, but is just trying to deploy from it.  The problem he is seeing is that the rPi2 is, I'm assuming, running out of RAM, probably because /tmp is in RAM or it's just trying to cache all of the packages into RAM before installing them.

I'll echo what @digiltd said:  you don't really need to deploy from the rPi2.  If you're thinking you needed to deploy from a Linux machine, you don't.  You can use any Windows, macOS, etc install you have.

Ultimately, the problem isn't with anything in the skill's sources though.  It's a problem with Amazon's deployment packages, and even then it's questionable whether it'd be called a 'problem'.  It's more that the rPi2 doesn't meet the minimum requirements for lambda-deploy.  Amazon might be able to modify it though if you bring it to their attention.

**Comment by fergalom** [comment]
True, trying to deploy from the Rpi2 and it tries to cache all packages in RAM before deploying which is a problem for small SBC like the rpi. 

Misplaced my issue, you are correct, it lies with lambda-deploy.
closed
