### ISSUE TITLE
Navigation commands in one session

### ISSUE THREAD

**Issue by m0ngr31** [m0ngr31/kodi-alexa#83]
I was just playing with keeping the session alive for navigating around the different menus. I'm not sure if it's a skill issue or something else, but I couldn't get it to keep alive past like 5 commands. Can anyone give this a shot and see what their's does? @jingai

**Comment by jingai** [comment]
I'll look at it in a couple days, but I really don't think it's going to work out quite as well as people are imagining/hoping.  I've played with games skills and such that keep the session open and find it pretty annoying.

Something else to think about (and probably more, since I haven't spent the time to think this through yet):  the 'stop' command is the most common one I've seen people use to end the session, but we utilize 'stop' to stop playback in Kodi in the skill.  I'm sure it's a violation of Amazon's guidelines, and one we could work around.. but I think it would require keeping track of the session in some way so we can distinguish between a single command and a 'conversation.'

**Comment by m0ngr31** [comment]
Yeah, I'm positive that's a violation of the guidelines, but since it's not being submitted, it's probably fine.

Keeping the session open for just certain type of commands shouldn't cause a problem with the Stop intent since we can store something in the session and just check beforehand.

**Comment by jingai** [comment]
Yeah, I just wanted to point out that we need to specially handle the "stop" command when the session is open.

We may also want to only allow navigation commands in an open session?  I haven't tested this yet, but I glanced at the commits briefly.. I believe it'd currently be possible to open the session with a navigation command, and then at some point during the session, issue an e.g. WatchMovie intent.  This would close the session and play the movie.

I can see an argument for either behavior, which is why I'm bringing it up.. on one hand, it might be unexpected that the session closes on the user, and on the other, it'd mean the user wouldn't get responses to commands they'd expect to work.

**Comment by m0ngr31** [comment]
This is fixed on the `flask-ask` branch.

**Comment by digiltd** [comment]
Cool, I also I started work on a "control mode" feature where it would start and stop the session

Something like:

user: "alexa ask Kodi to activate remote control"

echo: "starting remote control mode, to use say "go up" "go back" as if you were pressing buttons, say "stop" to exit control mode"

She would also reprompt if not heard a control command for a while and exit after a timeout.

The flask-ask change does affect this slightly, but the concept of starting and stopping a "remote control mode" tested ok.

**Comment by m0ngr31** [comment]
I like that idea. That gives them a clear expectation with when the session closes and stays open. I can write that in about 10 minutes with the current setup.

**Comment by m0ngr31** [comment]
@digiltd I added that in the new branch. Thanks for the suggestion.
